### ISSUE TITLE
Missing "Enable Line" Button? (Windows64)

### ISSUE THREAD

**Issue by wenshin2** [ChangSpivey/SubtitleMemorize#2]
I only see the "Disable Line" button, it seems to be missing the "Enable Line" button? 
![image](https://user-images.githubusercontent.com/17095418/45356514-06795f80-b5f6-11e8-935f-15aaad764fd4.png)

I'm also getting a warning on the console: Gtk-Warning **: Invalid Icon Size 0

Right now I can't enable a line if it's greyed out. Hopefully there's an easy way to fix this?

**Comment by kaegi** [comment]
You can change the behavior of some buttons by holding Ctrl or Shift (or both at once). Pressing Ctrl will change the "Disable Line" to "Enable Line".

The Gtk-Warning can safely be ignored.

**Comment by wenshin2** [comment]
That works, thank you! 
Since this isn't actually a bug, I'll close this issue.
